package com.epam.lab.mentoring.webservice.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-03-14T21:23:03.676+03:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "FileSharingWebService",
                  wsdlLocation = "file:/L:/Mentoring/AliaksandrShynkevichGroup/homework4/soap-client/src/main/resources/soap-schema.wsdl",
                  targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/") 
public class FileSharingWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.webservice.mentoring.lab.epam.com/", "FileSharingWebService");
    public final static QName FileSharingWebServicePort = new QName("http://soap.webservice.mentoring.lab.epam.com/", "FileSharingWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/L:/Mentoring/AliaksandrShynkevichGroup/homework4/soap-client/src/main/resources/soap-schema.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FileSharingWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/L:/Mentoring/AliaksandrShynkevichGroup/homework4/soap-client/src/main/resources/soap-schema.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FileSharingWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileSharingWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileSharingWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FileSharingWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FileSharingWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FileSharingWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IFileSharingWebService
     */
    @WebEndpoint(name = "FileSharingWebServicePort")
    public IFileSharingWebService getFileSharingWebServicePort() {
        return super.getPort(FileSharingWebServicePort, IFileSharingWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFileSharingWebService
     */
    @WebEndpoint(name = "FileSharingWebServicePort")
    public IFileSharingWebService getFileSharingWebServicePort(WebServiceFeature... features) {
        return super.getPort(FileSharingWebServicePort, IFileSharingWebService.class, features);
    }

}
