package com.epam.lab.mentoring.webservice.soap;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-03-14T21:25:48.782+03:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", name = "IFileSharingWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IFileSharingWebService {

    @WebMethod
    @RequestWrapper(localName = "listResources", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.ListResources")
    @ResponseWrapper(localName = "listResourcesResponse", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.ListResourcesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listResources();
}
