package com.epam.lab.mentoring.webservice.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-03-14T21:38:49.354+03:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", name = "IFileSharingWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IFileSharingWebService {

    @WebMethod
    @RequestWrapper(localName = "deleteFile", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.DeleteFile")
    @ResponseWrapper(localName = "deleteFileResponse", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.DeleteFileResponse")
    public void deleteFile(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "listFiles", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.ListFiles")
    @ResponseWrapper(localName = "listFilesResponse", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.ListFilesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listFiles();

    @WebMethod
    @RequestWrapper(localName = "createFile", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.CreateFile")
    @ResponseWrapper(localName = "createFileResponse", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.CreateFileResponse")
    public void createFile(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1
    );

    @WebMethod
    @RequestWrapper(localName = "readFile", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.ReadFile")
    @ResponseWrapper(localName = "readFileResponse", targetNamespace = "http://soap.webservice.mentoring.lab.epam.com/", className = "com.epam.lab.mentoring.webservice.soap.ReadFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] readFile(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
